### ISSUE TITLE
Unable to install v2.5.1 on MackBook M1 with Monterey

### ISSUE THREAD

**Issue by borexino** [picrust/picrust2#287] opened 2022-11-14 13:06 UTC
Hi,
I ran this:
`micromamba create -n picrust2 -c bioconda -c conda-forge picrust2=2.5.1`

and I received this:
```
sonnybook@MacBook-Pro-14 ~ % micromamba create -n picrust2 -c bioconda -c conda-forge picrust2=2.5.1

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

warning  libmamba 'root_prefix' set with default value: /Users/sonnybook/micromamba
bioconda/osx-arm64                                 124.0 B @ 454.0 B/s  0.3s
bioconda/noarch                                      4.1MB @ 218.1kB/s 18.9s
conda-forge/osx-arm64                                4.2MB @ 209.6kB/s 20.1s
conda-forge/noarch                                  10.2MB @ 339.9kB/s 30.4s
Encountered problems while solving:
  - nothing provides biom-format >=2.1.10 needed by picrust2-2.5.1-pyhdfd78af_0

The environment can't be solved, aborting the operation
error    libmamba Could not solve for environment specs
critical libmamba UnsatisfiableError
sonnybook@MacBook-Pro-14 ~ % 
```
I ran also in Rosetta mode. Same issue.

**Comment by gavinmdouglas** [comment] 2022-11-14 13:17
Hey @borexino.

I haven't tried `micromamba` myself, but I can confirm that the command you posted works for me on my M1 chip Mac running Monterey when I swap `mamba` for `micromamba` (with `mamba` v0.25.0 and `conda` v22.9.0). Does that work for you?


Cheers,

Gavin

**Comment by borexino** [comment] 2022-11-14 15:08
Hi @gavinmdouglas  Thank for helping me! Here the output of `mamba create -n picrust2 -c bioconda -c conda-forge picrust2=2.5.1`

Terminal:

```
                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.0.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['picrust2=2.5.1']

pkgs/main/osx-arm64                                           No change
bioconda/osx-arm64                                            No change
bioconda/noarch                                               No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/r/osx-arm64                                              No change
conda-forge/osx-arm64                                4.2MB @   2.3MB/s  1.9s
conda-forge/noarch                                  10.2MB @   3.4MB/s  3.3s
Encountered problems while solving:
  - nothing provides biom-format >=2.1.10 needed by picrust2-2.5.1-pyhdfd78af_0
```


What I can do?

**Comment by borexino** [comment] 2022-11-14 15:59
It is strange! When I try to install different `picrust2` version I received:
` picrust2=2.5.0 `  ->   `- nothing provides epa-ng 0.3.8.* needed by picrust2-2.5.0-pyhdfd78af_0`
` picrust2=2.4.2 `  ->   `- nothing provides epa-ng 0.3.8.* needed by picrust2-2.4.2-pyhdfd78af_0`
` picrust2=2.4.0 `  ->   `- nothing provides python >=3.5,<3.7 needed by picrust2-2.4.0-py_0`

**Comment by gavinmdouglas** [comment] 2022-11-14 19:02
Ah ok, it looks like you might have a general conda issue. I installed miniconda on the command-line manually with the installation bash script they provided and it seems to work fine. Maybe that would work better than the version installed through homebrew?

I'm going to close this for now though, but please let me know if you think it's a problem with the PICRUSt2 installation specfically.

**Comment by borexino** [comment] 2022-11-15 07:31
Thanks @gavinmdouglas. I've understood that this is a known bug of conda/python. 
Bugs in this ambient are the major reason of my switch to R!
Thanks

**Comment by borexino** [comment] 2022-11-18 10:04
Sorry for coming back here. but after several bounces I landed on [mamba-org](https://github.com/mamba-org/mamba/issues/2120#issuecomment-1319424073) where I was informed that osx-arm64 build `biom-format` does not exist on the [conda channels](https://anaconda.org/search?q=biom-format).
Can you please re-open this ticket?
Thanks

**Comment by gavinmdouglas** [comment] 2022-11-18 11:34
Ah I see - I'm not sure what it worked for me on my laptop with an M1 chip then.

**Comment by borexino** [comment] 2022-11-18 13:25
Thanks for helping me!

**Comment by borexino** [comment] 2023-01-13 14:05
Is this notification from [biom-format](https://github.com/biocore/biom-format/issues/890#issuecomment-1375870398) useful?

**Comment by gavinmdouglas** [comment] 2023-04-07 13:29
Hi there,

I wasn't able to find any issue with biom-format, but I can confirm that the newest release, v2.5.2, also installs on my MacBook M1 running Monterey.


Cheers,

Gavin

**Comment by lcamVz** [comment] 2023-06-22 18:25
> Hi there,
> 
> I wasn't able to find any issue with biom-format, but I can confirm that the newest release, v2.5.2, also installs on my MacBook M1 running Ventura (and 2.5.1 was installable previously with Monterey).
> 
> Cheers,
> 
> Gavin

I am trying to install v2.5.2 how you manage to install it? @gavinmdouglas

**Comment by scmicrosys** [comment] 2023-07-17 12:11
Hello, 

Here is my solution for PICRUSt installation on M1 (MacStudio) with Ventura 13.4.1.

1. Install the dynamic binary translator Rosetta  and miniconda3 x86 (https://taylorreiter.github.io/2022-04-05-Managing-multiple-architecture-specific-installations-of-conda-on-apple-M1/).

2. Initialise x86 architecture emulator.

3. Follow "Install from source" available at https://github.com/picrust/picrust2/wiki/Installation.

wget https://github.com/picrust/picrust2/archive/v2.5.2.tar.gz
tar xvzf  v2.5.2.tar.gz
cd picrust2-2.5.2/
conda env create -f picrust2-env.yaml
conda activate picrust2
pip install --editable .
pytest

Cheers, 
silviac

**Comment by R-Wright-1** [comment] 2024-03-15 18:29
Hello, I'm just adding what I found works for Mac M1 here too: #314 

I'll close this issue, but please let me know if there are any additional issues not solved with any of the existing fixes.

**Closed by R-Wright-1** 2024-03-15 18:29 UTC
